FORMAT: 1A
# Zoo API

This is a test/prototype API all about zoo animals, so I can try out https://apiary.io/

# Group Animals

## Animal Collection [/animals]

### GET

+ Response 200 (application/json)
    + Attributes
        - animals (array[Animal])

## Animals Resource [/animals/{name}]

+ Parameters
  + name: `Malcom` - The unique type of animal

### GET

+ Response 200 (application/json)
    + Attributes
        - animal (Animal)

### PUT

+ Request (application/json)
    + Attributes
        - animals (Animal)

+ Response 200 (application/json)
    + Attributes
        - animals (Animal)

### DELETE

+ Response 204


# Data Structures

## Animal (object)

- name: `Malcom` (string, required) - Unique name of the animal.
- type: `Monkey` (string, required) - The type of animal.
- status (enum[string])
  - wild - The animal is currently in the wild. 
  - transport - The animal is in transport to the zoo.
  - zoo - The animal is in the zoo.
- created_at: `2015-01-07T14:03:43Z` (string, required) - ISO8601 date and time of when the animal was created.